version: "3.6"

services:
  postgres-pgvector:
    image: ankane/pgvector:latest
    container_name: hire-smart-ai-postgres-pgvector
    restart: always
    volumes:
      - postgres_pgvector_volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hire-smart-ai
    restart: always
    ports:
      - "8007:8007"
    volumes:
      - .:/app
    environment:
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBNAME=${DBNAME}
    depends_on:
      - postgres-pgvector
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_pgvector_volume:
